name: huntube_app
description: "Huntube portfolio project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+1

environment:
  sdk: '>=3.4.3 <4.0.0'

isar_version: &isar_version ^3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  auto_route: ^8.1.3
  isar: *isar_version
  isar_flutter_libs: *isar_version
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  riverpod_generator: ^2.4.0
  isar_generator: *isar_version

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/huntube_icon.jpg"

flutter_icons:
  image_path: "assets/images/huntube_icon.jpg"
  ios: true
  android: true

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/text_files/
    - assets/audios/
    - assets/images/
  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/fonts/lalezar/Lalezar-Regular.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800
